.PHONY: install
# installs requirements.txt
install:
	python3 -m pip install -r req.txt

.PHONY: run
# run the hello world server
run:
	python3 main.py

.PHONY: test
# runs unit tests
test:
	python3 -m pytest
